apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/kubernetes-id: ${{ values.name | dump }}
  links:
    - url: https://${{ values.host }}
      title: Ambiente
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
